# Generated by Django 6.0.3 on 2026-05-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_intern_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='certifications_summary',
            field=models.TextField(blank=True, help_text='Comma separated certifications'),
        ),
        migrations.AddField(
            model_name='intern',
            name='college_university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='intern',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='intern',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
