# Generated by Django 5.2.14 on 2026-05-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0003_intern_certifications_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='intern',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
