# Generated by Django 6.0.3 on 2026-05-19 08:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_screenshot'),
        ),
    ]
