# Generated by Django 6.0.3 on 2026-05-25 04:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0006_alter_intern_payment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('sales', 'Sales'), ('data_science', 'Data Science'), ('product', 'Product Management'), ('other', 'Other')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_screenshot', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_screenshot')),
                ('date_joined', models.DateTimeField()),
                ('date_rejected', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rejected Candidate',
                'verbose_name_plural': 'Rejected Candidates',
                'ordering': ['-date_rejected'],
            },
        ),
    ]
