# Generated by Django 6.0.3 on 2026-05-25 04:30

from django.db import migrations

def migrate_rejected_candidates(apps, schema_editor):
    Intern = apps.get_model('interns', 'Intern')
    RejectedCandidate = apps.get_model('interns', 'RejectedCandidate')
    
    rejected_interns = Intern.objects.filter(status='rejected')
    for intern in rejected_interns:
        RejectedCandidate.objects.create(
            full_name=intern.full_name,
            email=intern.email,
            department=intern.department,
            transaction_id=intern.transaction_id,
            payment_screenshot=intern.payment_screenshot,
            date_joined=intern.date_joined
        )
        intern.delete()

def reverse_migrate_rejected_candidates(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0007_rejectedcandidate'),
    ]

    operations = [
        migrations.RunPython(migrate_rejected_candidates, reverse_migrate_rejected_candidates),
    ]
