# Generated by Django 6.0.3 on 2026-05-27 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0008_auto_20260525_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allocated_interns',
            field=models.ManyToManyField(blank=True, related_name='allocated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
