# Generated by Django 5.2.14 on 2026-05-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0009_project_allocated_interns_project_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('senior_architect', 'Senior Architect'), ('admin', 'Admin')], default='intern', max_length=20),
        ),
    ]
