# Generated by Django 5.2.14 on 2026-05-28 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0010_intern_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=150)),
                ('allocation_percentage', models.PositiveIntegerField(default=100)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='interns.project')),
            ],
            options={
                'verbose_name': 'Project Allocation',
                'verbose_name_plural': 'Project Allocations',
                'unique_together': {('project', 'intern')},
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='allocated_interns',
        ),
        migrations.AddField(
            model_name='project',
            name='allocated_interns',
            field=models.ManyToManyField(blank=True, related_name='allocated_projects', through='interns.ProjectAllocation', to=settings.AUTH_USER_MODEL),
        ),
    ]
