# Generated by Django 5.2.14 on 2026-05-29 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0011_projectallocation_alter_project_allocated_interns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('role', models.CharField(choices=[('designer', 'Designer'), ('developer', 'Developer'), ('tester', 'Tester'), ('manager', 'Manager'), ('other', 'Other')], default='developer', max_length=50)),
                ('technology_stack', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='interns.project')),
            ],
            options={
                'verbose_name': 'Progress Report',
                'verbose_name_plural': 'Progress Reports',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
