# Generated by Django 6.0.3 on 2026-05-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0012_progressreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='timeline',
            new_name='project_category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='budget',
            new_name='tech_stack',
        ),
    ]
