# Generated by Django 6.0.3 on 2026-06-01 03:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0013_rename_timeline_project_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo'),
        ),
    ]
