# Generated by Django 6.0.3 on 2026-06-01 03:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0014_alter_intern_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resume'),
        ),
    ]
