# Generated by Django 5.2.14 on 2026-06-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0015_alter_intern_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='pf_account_number',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='pf_uan',
        ),
    ]
